
//-----------------------------------------------------------------------------
/*!
   \brief       auto generated file, containing module- and function-index defines

   \implementation
   copyright   STW (c) 1999-200x
   license     use only under terms of contract / confidential

   created     29.07.2015  XSLT processor
   \endimplementation

*/
//-----------------------------------------------------------------------------



#ifndef _ESX3XM_LIB_2_03R1_DEF_H
#define _ESX3XM_LIB_2_03R1_DEF_H

/* -- Defines ------------------------------------------------------------- */

#define X_CAN_IDX                                              (0)
   #define X_CAN_BUS_CHANGE_BUSOFF_TIME_IDX                    (0)
   #define X_CAN_BUS_CLOSE_IDX                                 (1)
   #define X_CAN_BUS_GET_STATUS_IDX                            (2)
   #define X_CAN_BUS_INIT_IDX                                  (3)
   #define X_CAN_BUS_INIT_FAILURE_CALLBACK_IDX                 (4)
   #define X_CAN_BUS_LOCK_IDX                                  (5)
   #define X_CAN_BUS_PERFORM_BUSOFF_RECOVERY_IDX               (6)
   #define X_CAN_BUS_SET_MASKS_IDX                             (8)
   #define X_CAN_OBJ_CLEAR_BUF_IDX                             (9)
   #define X_CAN_OBJ_CLOSE_IDX                                 (10)
   #define X_CAN_OBJ_GET_BUF_COUNT_IDX                         (11)
   #define X_CAN_OBJ_GET_MSG_IDX                               (12)
   #define X_CAN_OBJ_GET_STATUS_IDX                            (13)
   #define X_CAN_OBJ_INIT_IDX                                  (14)
   #define X_CAN_OBJ_INIT_GATEWAY_IDX                          (15)
   #define X_CAN_OBJ_LOCK_IDX                                  (16)
   #define X_CAN_OBJ_SEND_MSG_IDX                              (17)
   #define X_CAN_OBJ_SEND_RTR_REQ_IDX                          (18)
   #define X_CAN_OBJ_SET_AUTO_RESPONSE_IDX                     (19)
   #define X_CAN_OBJ_SET_FILTER_IDX                            (20)
   #define X_CAN_OBJ_SET_PAUSE_IDX                             (21)
   #define X_CAN_SELF_TEST_IDX                                 (22)
   #define X_CAN_BUS_INIT_EXT_IDX                              (23)
   #define X_CAN_BUS_GET_SAMPLE_POINT_IDX                      (24)

#define X_EEP_IDX                                              (1)
   #define X_EEP_FLUSH_IDX                                     (0)
   #define X_EEP_READ_IDX                                      (1)
   #define X_EEP_WRITE_IDX                                     (2)
   #define X_EEP_GET_STATUS_IDX                                (3)

#define X_IN_IDX                                               (2)
   #define X_IN_GET_DUTY_CYCLE_IDX                             (0)
   #define X_IN_GET_FREQUENCY_IDX                              (1)
   #define X_IN_GET_RAW_VALUE_IDX                              (2)
   #define X_IN_GET_STATUS_IDX                                 (3)
   #define X_IN_GET_VALUE_IDX                                  (4)
   #define X_IN_INIT_IDX                                       (5)
   #define X_IN_GET_COUNTER_IDX                                (6)
   #define X_IN_SET_COUNTER_IDX                                (7)
   #define X_IN_GET_COUNTER_DIRECTION_IDX                      (8)
   #define X_T_IN_INIT_FREQUENCY_AVG_IDX                       (9)
   #define X_T_IN_GET_FREQUENCY_AVG_IDX                        (10)

#define X_OS_IDX                                               (3)
   #define X_OS_INIT_IDX                                       (4)
   #define X_OS_INSTALL_TASK_IDX                               (5)
   #define X_OS_INSTALL_TASK_EXT_IDX                           (6)
   #define X_OS_SET_TASK_TIMER_EXT_IDX                         (7)
   #define X_OS_SET_TASK_TIMER_IDX                             (8)
   #define X_OS_START_IDX                                      (9)
   #define X_OS_CHECK_TASK_STACK_IDX                           (10)
   #define X_OS_MBOX_INIT_IDX                                  (11)
   #define X_OS_MBOX_CLOSE_IDX                                 (12)
   #define X_OS_MBOX_GET_MESSAGE_IDX                           (13)
   #define X_OS_MBOX_SEND_MESSAGE_IDX                          (14)
   #define X_OS_MUTEX_INIT_IDX                                 (15)
   #define X_OS_MUTEX_CLOSE_IDX                                (16)
   #define X_OS_MUTEX_GET_IDX                                  (17)
   #define X_OS_MUTEX_RELEASE_IDX                              (18)
   #define X_OS_SEMA_INIT_IDX                                  (19)
   #define X_OS_SEMA_CLOSE_IDX                                 (20)
   #define X_OS_SEMA_GET_IDX                                   (21)
   #define X_OS_SEMA_RELEASE_IDX                               (22)
   #define X_OS_SIGNAL_INIT_IDX                                (23)
   #define X_OS_SIGNAL_CLOSE_IDX                               (24)
   #define X_OS_SIGNAL_WAIT_FOR_IDX                            (25)
   #define X_OS_SIGNAL_SEND_IDX                                (26)
   #define X_OS_SUSPEND_TASK_IDX                               (30)
   #define X_OS_RESUME_TASK_IDX                                (31)
   #define X_OS_DELETE_TASK_IDX                                (32)
   #define X_OS_CHECK_TASK_STACK_EXT_IDX                       (33)

#define X_OUT_IDX                                              (4)
   #define X_OUT_GET_CURRENT_IDX                               (0)
   #define X_OUT_GET_STATUS_IDX                                (1)
   #define X_OUT_INIT_IDX                                      (2)
   #define X_OUT_RESET_ERROR_IDX                               (3)
   #define X_OUT_SET_FREQUENCY_IDX                             (4)
   #define X_OUT_SET_VALUE_IDX                                 (5)
   #define X_OUT_SET_CONTROL_PARAMETERS_IDX                    (6)
   #define X_OUT_GET_CONTROL_PARAMETERS_IDX                    (7)
   #define X_OUT_SET_VALUE_RAMPING_IDX                         (8)
   #define X_OUT_RELAY_INIT_IDX                                (20)
   #define X_OUT_RELAY_SET_IDX                                 (21)
   #define X_OUT_RELAY_SET_ALL_IDX                             (22)
   #define X_OUT_RELAY_GET_STATUS_IDX                          (23)
   #define X_OUT_RELAY_RESET_ERROR_IDX                         (24)

#define X_SER_IDX                                              (5)
   #define X_SER_CLEAR_RX_BUF_IDX                              (0)
   #define X_SER_CLEAR_TX_BUF_IDX                              (1)
   #define X_SER_CLOSE_IDX                                     (2)
   #define X_SER_GET_RX_BUF_COUNT_IDX                          (3)
   #define X_SER_GET_STATUS_IDX                                (4)
   #define X_SER_GET_TX_BUF_COUNT_IDX                          (5)
   #define X_SER_INIT_IDX                                      (6)
   #define X_SER_INIT_RX_BUF_IDX                               (7)
   #define X_SER_INIT_TX_BUF_IDX                               (8)
   #define X_SER_READ_IDX                                      (9)
   #define X_SER_SET_BITRATE_IDX                               (10)
   #define X_SER_WRITE_IDX                                     (11)
   #define X_SER_WRITE_STRING_IDX                              (12)

#define X_SYS_IDX                                              (6)
   #define X_SYS_CLOSE_IDX                                     (0)
   #define X_SYS_GET_ADC_FILTER_IDX                            (2)
   #define X_SYS_GET_ADC_VALUE_IDX                             (3)
   #define X_SYS_GET_ADC_VALUE_SCALED_IDX                      (4)
   #define X_SYS_GET_TEMPERATURE_IDX                           (6)
   #define X_SYS_SET_ADC_FILTER_IDX                            (7)
   #define X_SYS_SET_ALL_RELAYS_IDX                            (8)
   #define X_SYS_SET_BEEPER_IDX                                (9)
   #define X_SYS_SET_LED_IDX                                   (10)
   #define X_SYS_SET_RELAY_IDX                                 (11)
   #define X_SYS_SET_SENSOR_SUPPLY_IDX                         (12)
   #define X_SYS_STAY_ALIVE_IDX                                (13)
   #define X_SYS_TRIGGER_CPU_WATCHDOG_IDX                      (14)
   #define X_SYS_GET_ADC_RAW_VALUE_IDX                         (16)
   #define X_SYS_GET_ADC_RAW_VALUE_SCALED_IDX                  (17)
   #define X_SYS_INIT_IDX                                      (18)
   #define X_SYS_GET_SYSTEM_INFORMATION_IDX                    (19)
   #define X_SYS_GET_IGNITION_IDX                              (20)
   #define X_SYS_INIT_OFF_REACTION_IDX                         (21)
   #define X_SYS_GET_COMPONENT_INFO_IDX                        (22)

#define X_UTI_IDX                                              (7)
   #define X_UTI_CALC_CRC_TRICORE_IDX                          (0)
   #define X_UTI_CALC_CRC_16_IDX                               (1)
   #define X_UTI_CALC_CRC_STW_IDX                              (2)

#define X_SSV_IDX                                              (8)
   #define X_SSV_INIT_IDX                                      (0)
   #define X_SSV_GET_STATUS_IDX                                (1)
   #define X_SSV_TRIGGER_IDX                                   (2)
   #define X_SSV_RESET_IDX                                     (3)
   #define X_SSV_SET_TRIGGER_IDX                               (4)

#define X_TIM_IDX                                              (9)
   #define X_TIM_INIT_IDX                                      (0)
   #define X_TIM_CLOSE_IDX                                     (1)
   #define X_TIM_SET_IDX                                       (2)

#define X_FL_IDX                                               (11)
   #define X_FL_GET_VERSION_IDX                                (1)
   #define X_FL_GET_NUM_INTERFACES_IDX                         (2)
   #define X_FL_GET_INTERFACE_PARAMETERS_IDX                   (3)
   #define X_FL_SET_INTERFACE_PARAMETERS_IDX                   (4)
   #define X_FL_GET_NUM_CHECKSUM_BLOCKS_IDX                    (5)
   #define X_FL_GET_CHECKSUM_BLOCK_ADDRESSES_IDX               (6)
   #define X_FL_SET_CHECKSUM_BLOCK_ADDRESSES_IDX               (7)
   #define X_FL_GET_CHECKSUM_BLOCK_CHECK_IDX                   (8)
   #define X_FL_SET_CHECKSUM_BLOCK_CHECK_IDX                   (9)
   #define X_FL_GET_FINGER_PRINT_IDX                           (10)
   #define X_FL_GET_CONTENT_CHANGED_FLAG_IDX                   (11)
   #define X_FL_PERFORM_SIGNATURE_BLOCK_CHECK_IDX              (12)
   #define X_FL_RESET_CONTENT_CHANGED_FLAG_IDX                 (13)

#define X_MPU_IDX                                              (12)
   #define X_MPU_INIT_IDX                                      (0)
   #define X_MPU_GET_STATUS_IDX                                (1)

#define XS_CAN_IDX                                             (100)
   #define XS_CAN_BUS_CHANGE_BUSOFF_TIME_IDX                   (0)
   #define XS_CAN_BUS_CLOSE_IDX                                (1)
   #define XS_CAN_BUS_INIT_IDX                                 (3)
   #define XS_CAN_BUS_INIT_FAILURE_CALLBACK_IDX                (4)
   #define XS_CAN_BUS_LOCK_IDX                                 (5)
   #define XS_CAN_BUS_PERFORM_BUSOFF_RECOVERY_IDX              (6)
   #define XS_CAN_BUS_SET_MASKS_IDX                            (8)
   #define XS_CAN_OBJ_CLEAR_BUF_IDX                            (9)
   #define XS_CAN_OBJ_CLOSE_IDX                                (10)
   #define XS_CAN_OBJ_GET_MSG_IDX                              (12)
   #define XS_CAN_OBJ_GET_STATUS_IDX                           (13)
   #define XS_CAN_OBJ_INIT_IDX                                 (14)
   #define XS_CAN_OBJ_INIT_GATEWAY_IDX                         (15)
   #define XS_CAN_OBJ_LOCK_IDX                                 (16)
   #define XS_CAN_OBJ_SEND_MSG_IDX                             (17)
   #define XS_CAN_OBJ_SEND_RTR_REQ_IDX                         (18)
   #define XS_CAN_OBJ_SET_AUTO_RESPONSE_IDX                    (19)
   #define XS_CAN_OBJ_SET_FILTER_IDX                           (20)
   #define XS_CAN_OBJ_SET_PAUSE_IDX                            (21)
   #define XS_CAN_SELF_TEST_IDX                                (22)
   #define XS_CAN_OBJ_GET_EVENT_HANDLE_IDX                     (23)
   #define XS_CAN_BUS_GET_BUSWARN_CHANNEL_IDX                  (24)
   #define XS_CAN_BUS_GET_BUSOFF_CHANNEL_IDX                   (25)
   #define XS_CAN_OBJ_EVENT_MASK_SET_IDX                       (26)
   #define XS_CAN_BUS_INIT_EXT_IDX                             (27)
   #define XS_CAN_BUS_GET_SAMPLE_POINT_IDX                     (28)

#define XS_EEP_IDX                                             (101)
   #define XS_EEP_FLUSH_IDX                                    (0)
   #define XS_EEP_WRITE_IDX                                    (2)

#define XS_IN_IDX                                              (102)
   #define XS_IN_INIT_IDX                                      (5)
   #define XS_IN_SET_COUNTER_IDX                               (7)
   #define XS_IN_GET_EVENT_CHANNEL_IDX                         (9)
   #define XS_T_IN_INIT_FREQUENCY_AVG_IDX                      (10)

#define XS_OS_IDX                                              (103)
   #define XS_OS_SET_TASK_SAFETY_LEVEL_IDX                     (2)
   #define XS_OS_GET_TASK_SAFETY_LEVEL_IDX                     (3)
   #define XS_OS_INIT_IDX                                      (4)
   #define XS_OS_INSTALL_TASK_EXT_IDX                          (6)
   #define XS_OS_SET_TASK_TIMER_EXT_IDX                        (7)
   #define XS_OS_MBOX_INIT_IDX                                 (11)
   #define XS_OS_MBOX_CLOSE_IDX                                (12)
   #define XS_OS_MBOX_GET_MESSAGE_IDX                          (13)
   #define XS_OS_MBOX_SEND_MESSAGE_IDX                         (14)
   #define XS_OS_MUTEX_INIT_IDX                                (15)
   #define XS_OS_MUTEX_CLOSE_IDX                               (16)
   #define XS_OS_MUTEX_GET_IDX                                 (17)
   #define XS_OS_MUTEX_RELEASE_IDX                             (18)
   #define XS_OS_SEMA_INIT_IDX                                 (19)
   #define XS_OS_SEMA_CLOSE_IDX                                (20)
   #define XS_OS_SEMA_GET_IDX                                  (21)
   #define XS_OS_SEMA_RELEASE_IDX                              (22)
   #define XS_OS_SIGNAL_INIT_IDX                               (23)
   #define XS_OS_SIGNAL_CLOSE_IDX                              (24)
   #define XS_OS_SIGNAL_WAIT_FOR_IDX                           (25)
   #define XS_OS_SIGNAL_SEND_IDX                               (26)
   #define XS_OS_SUSPEND_TASK_IDX                              (30)
   #define XS_OS_RESUME_TASK_IDX                               (31)
   #define XS_OS_DELETE_TASK_IDX                               (32)
   #define XS_OS_MBOX_INIT_UNPROTECTED_IDX                     (35)
   #define XS_OS_MUTEX_INIT_UNPROTECTED_IDX                    (36)
   #define XS_OS_SEMA_INIT_UNPROTECTED_IDX                     (37)
   #define XS_OS_SIGNAL_INIT_UNPROTECTED_IDX                   (38)

#define XS_OUT_IDX                                             (104)
   #define XS_OUT_INIT_IDX                                     (1)
   #define XS_OUT_INIT_UNPROTECTED_IDX                         (2)
   #define XS_OUT_RESET_ERROR_IDX                              (3)
   #define XS_OUT_SET_FREQUENCY_IDX                            (4)
   #define XS_OUT_SET_VALUE_IDX                                (5)
   #define XS_OUT_SET_CONTROL_PARAMETERS_IDX                   (6)
   #define XS_OUT_SET_VALUE_RAMPING_IDX                        (8)
   #define XS_OUT_GET_OVERCURRENT_CHANNEL_IDX                  (9)
   #define XS_OUT_GET_RECOVERY_CHANNEL_IDX                     (10)
   #define XS_OUT_GET_EVENT_CHANNEL_IDX                        (11)
   #define XS_OUT_RELAY_INIT_IDX                               (20)
   #define XS_OUT_RELAY_SET_IDX                                (21)
   #define XS_OUT_RELAY_SET_ALL_IDX                            (22)
   #define XS_OUT_RELAY_RESET_ERROR_IDX                        (24)
   #define XS_OUT_RELAY_GET_EVENT_CHANNEL_IDX                  (25)

#define XS_SER_IDX                                             (105)
   #define XS_SER_CLEAR_RX_BUF_IDX                             (0)
   #define XS_SER_CLEAR_TX_BUF_IDX                             (1)
   #define XS_SER_CLOSE_IDX                                    (2)
   #define XS_SER_GET_STATUS_IDX                               (4)
   #define XS_SER_INIT_IDX                                     (6)
   #define XS_SER_INIT_RX_BUF_IDX                              (7)
   #define XS_SER_INIT_TX_BUF_IDX                              (8)
   #define XS_SER_READ_IDX                                     (9)
   #define XS_SER_SET_BITRATE_IDX                              (10)
   #define XS_SER_WRITE_IDX                                    (11)
   #define XS_SER_WRITE_STRING_IDX                             (12)

#define XS_SYS_IDX                                             (106)
   #define XS_SYS_CLOSE_IDX                                    (0)
   #define XS_SYS_SET_ADC_FILTER_IDX                           (7)
   #define XS_SYS_SET_ALL_RELAYS_IDX                           (8)
   #define XS_SYS_SET_LED_IDX                                  (10)
   #define XS_SYS_SET_RELAY_IDX                                (11)
   #define XS_SYS_SET_SENSOR_SUPPLY_IDX                        (12)
   #define XS_SYS_STAY_ALIVE_IDX                               (13)
   #define XS_SYS_TRIGGER_CPU_WATCHDOG_IDX                     (14)
   #define XS_SYS_INIT_OFF_REACTION_IDX                        (21)

#define XS_SSV_IDX                                             (108)
   #define XS_SSV_INIT_IDX                                     (0)
   #define XS_SSV_GET_STATUS_IDX                               (1)
   #define XS_SSV_SET_TRIGGER_IDX                              (4)

#define XS_ERR_IDX                                             (110)
   #define XS_ERR_INIT_IDX                                     (0)
   #define XS_ERR_GET_ERR_EVENT_IDX                            (1)
   #define XS_ERR_CLOSE_IDX                                    (2)

#define XS_FL_IDX                                              (111)
   #define XS_FL_SET_INTERFACE_PARAMETERS_IDX                  (4)
   #define XS_FL_SET_CHECKSUM_BLOCK_ADDRESSES_IDX              (7)
   #define XS_FL_SET_CHECKSUM_BLOCK_CHECK_IDX                  (9)
   #define XS_FL_RESET_CONTENT_CHANGED_FLAG_IDX                (13)

#define XS_MPU_IDX                                             (112)
   #define XS_MPU_INIT_IDX                                     (0)
   #define XS_MPU_GET_MEM_PROTECTION_IDX                       (1)

#define XS_DP_IDX                                              (113)
   #define XS_DP_INIT_IDX                                      (0)
   #define XS_DP_GET_INSTANCE_IDX                              (1)
   #define XS_DP_WRITE_IDX                                     (2)
   #define XS_DP_READ_IDX                                      (3)

#define XS_AM_IDX                                              (114)
   #define XS_AM_INIT_IDX                                      (0)
   #define XS_AM_MODULE_SET_PERMISSION_IDX                     (1)
   #define XS_AM_FUNCTION_SET_PERMISSION_IDX                   (3)
   #define XS_AM_DATAPOOL_SET_PERMISSION_IDX                   (4)

#define XS_EB_IDX                                              (115)
   #define XS_EB_ENABLE_NONINTERFERING_ACCESS_IDX              (0)


#endif   // _ESX3XM_LIB_2_03R1_DEF_H
